configurations:
    closed:
        hand: [2.443, 2.443, 2.443, 0.0]
    open:
        hand: [0., 0., 0., 0.]
    bowl_grasp:
        hand: [0.977, 0.977, 0.977, 0.0]
    glass_grasp:
        hand: [0.488, 0.488, 0.488, 0.0]
    tray_handle_grasp:
        hand: [0.977, 0.977, 0.977, 0.0]
    plate_slide:
        hand: [0.684, 0.684, 0.684, 0.0]
    plate_grasp:
        hand: [0.976, 0.976, 0.976, 0.0]
    block_grasp_preshape:
        hand: [1.7, 1.7, 0.2, 2.45]
    block_grasp:
        hand: [1.7, 1.7, 1.7, 2.45]
    